<?php

namespace AppBundle\Repository;

/**
 * OneActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneActiviteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Récupération des activités
     * @return array
     */
    public function getActivites() {
        $activites = $this
                ->createQueryBuilder('activite')
                ->orderBy('activite.nom')
                ->getQuery()
                ->getResult();
        return $activites;
    }
}
