<?php

namespace AppBundle\Repository;

/**
 * OneCommandeDevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneCommandeDevisRepository extends \Doctrine\ORM\EntityRepository
{
}
