<?php

namespace AppBundle\Repository;

/**
 * OneModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneDocumentModeleRepository extends \Doctrine\ORM\EntityRepository
{
}
