<?php

namespace AppBundle\Repository;

/**
 * OneDeviseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneDeviseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDevises() {
        $devises = $this
                ->createQueryBuilder('devise')
                ->orderBy('devise.nom')
                ->getQuery()
                ->getResult();
        return $devises;
    }
}
