<?php

namespace AppBundle\Repository;

/**
 * OneFormeJuridiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneFormeJuridiqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLegalForms() {
        $formesJuridiques = $this
                ->createQueryBuilder('forme')
                ->orderBy('forme.libelle')
                ->getQuery()
                ->getResult();
        return $formesJuridiques;
    }
}
