<?php

namespace AppBundle\Repository;

/**
 * OneInvoiceDevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneInvoiceDevisRepository extends \Doctrine\ORM\EntityRepository
{
}
