<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Dossier;

/**
 * OneModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneModeleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getModeles() {
        $modeles = $this
                ->createQueryBuilder('modele')
                ->orderBy('modele.id')
                ->getQuery()
                ->getResult();
        return $modeles;
    }

    public function getModelesByDossier(Dossier $dossier = null){
        return $this
            ->createQueryBuilder('modele')
            ->where('modele.dossier = :dossier or modele.dossier is null')
            ->setParameter('dossier', $dossier)
            ->getQuery()
            ->getResult();
    }
}
