<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OneMoyenPaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneMoyenPaiementRepository extends EntityRepository
{
    public function getMoyenPaiements() {
        $types = $this
                ->createQueryBuilder('paiement')
                ->orderBy('paiement.nom')
                ->getQuery()
                ->getResult();
        return $types;
    }
}
