<?php

namespace AppBundle\Repository;

/**
 * OneParametreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneParametreRepository extends \Doctrine\ORM\EntityRepository
{
}
