<?php

namespace AppBundle\Repository;

/**
 * OneTvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneTvaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTva() {
        return $this
                ->createQueryBuilder('tva')
                ->orderBy('tva.taux')
                ->getQuery()
                ->getResult();
    }
}
